package contract

// Every entry must suppress a current pre-waiver violation; C-WAIVE-001 rejects stale register entries.
waivers: [#WaiverId]: #Waiver
waivers: {
	"W-TEST-GDSCRIPT": {id: "W-TEST-GDSCRIPT", invariant: "C-TEST-006", subject: "gdscript", reason: "Godot owns the TCP server lifecycle and no hermetic fixture exists.", reference: "proj/cue/plan.md#2.9", added: "2026-07-24"}
	"W-TEST-JEDI": {id: "W-TEST-JEDI", invariant: "C-TEST-006", subject: "python_jedi", reason: "The alternate has no dedicated collected test surface.", reference: "proj/cue/plan.md#2.9", added: "2026-07-24"}
	"W-TEST-SOLARGRAPH": {id: "W-TEST-SOLARGRAPH", invariant: "C-TEST-006", subject: "ruby_solargraph", reason: "The alternate has no dedicated collected test surface.", reference: "proj/cue/plan.md#2.9", added: "2026-07-24"}
	"W-TEST-VTS": {id: "W-TEST-VTS", invariant: "C-TEST-006", subject: "typescript_vts", reason: "The alternate has no dedicated collected test surface.", reference: "proj/cue/plan.md#2.9", added: "2026-07-24"}
	"W-TEST-OMNISHARP": {id: "W-TEST-OMNISHARP", invariant: "C-TEST-006", subject: "csharp_omnisharp", reason: "The alternate has no dedicated collected test surface.", reference: "proj/cue/plan.md#2.9", added: "2026-07-24"}
	"W-TEST-DUP-ALIAS": {id: "W-TEST-DUP-ALIAS", invariant: "C-TEST-005", subject: "python_ty", reason: "The live alias dictionary contains a duplicate PYTHON_TY literal.", reference: "test/conftest.py#_LANGUAGE_REPO_ALIASES", added: "2026-07-24"}
	"W-REG-TEMPLATE-STALE": {id: "W-REG-TEMPLATE-STALE", invariant: "C-REG-007", subject: "project.template.yml", reason: "The generated template list remains stale until P9 regeneration.", reference: "proj/cue/plan.md#P9", added: "2026-07-24"}

	"W-PROV-JULIA-UNPINNED": {id: "W-PROV-JULIA-UNPINNED", invariant: "C-PROV-004", subject: "julia", reason: "Runtime provisioning delegates to Julia Pkg without a contract-enforceable package version.", reference: "src/solidlsp/language_servers/julia_server.py", added: "2026-07-24"}
	"W-PROV-NIXD-UNPINNED": {id: "W-PROV-NIXD-UNPINNED", invariant: "C-PROV-004", subject: "nix", reason: "The workflow installs nixd from the moving nixos-unstable channel.", reference: ".github/workflows/pytest.yml#Install nixd (Nix Language Server)", added: "2026-07-24"}

	"W-PROV-COVERAGE-ADA": {id: "W-PROV-COVERAGE-ADA", invariant: "C-PROV-005", subject: "ada:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/ada_language_server.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-AL": {id: "W-PROV-COVERAGE-AL", invariant: "C-PROV-005", subject: "al:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/al_language_server.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-BASH": {id: "W-PROV-COVERAGE-BASH", invariant: "C-PROV-005", subject: "bash:coverage-opaque", reason: "Imperative companion download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/bash_language_server.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-GROOVY": {id: "W-PROV-COVERAGE-GROOVY", invariant: "C-PROV-005", subject: "groovy:coverage-opaque", reason: "Imperative companion download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/groovy_language_server.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-HAXE": {id: "W-PROV-COVERAGE-HAXE", invariant: "C-PROV-005", subject: "haxe:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/haxe_language_server.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-JAVA": {id: "W-PROV-COVERAGE-JAVA", invariant: "C-PROV-005", subject: "java:coverage-opaque", reason: "Imperative multi-artifact provisioning prevents AST extraction of complete component-level per-OS evidence.", reference: "src/solidlsp/language_servers/eclipse_jdtls.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-KOTLIN": {id: "W-PROV-COVERAGE-KOTLIN", invariant: "C-PROV-005", subject: "kotlin:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/kotlin_language_server.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-LUA": {id: "W-PROV-COVERAGE-LUA", invariant: "C-PROV-005", subject: "lua:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/lua_ls.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-LUAU": {id: "W-PROV-COVERAGE-LUAU", invariant: "C-PROV-005", subject: "luau:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/luau_lsp.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-MATLAB": {id: "W-PROV-COVERAGE-MATLAB", invariant: "C-PROV-005", subject: "matlab:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/matlab_language_server.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-PHPACTOR": {id: "W-PROV-COVERAGE-PHPACTOR", invariant: "C-PROV-005", subject: "php_phpactor:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/phpactor.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-POWERSHELL": {id: "W-PROV-COVERAGE-POWERSHELL", invariant: "C-PROV-005", subject: "powershell:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/powershell_language_server.py", added: "2026-07-24"}
	"W-PROV-COVERAGE-TOML": {id: "W-PROV-COVERAGE-TOML", invariant: "C-PROV-005", subject: "toml:coverage-opaque", reason: "Imperative download construction prevents AST extraction of complete per-OS provisioning evidence.", reference: "src/solidlsp/language_servers/taplo_server.py", added: "2026-07-24"}

	"W-PROV-CHECKSUM-ADA": {id: "W-PROV-CHECKSUM-ADA", invariant: "C-PROV-003", subject: "ada:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/ada_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-AL": {id: "W-PROV-CHECKSUM-AL", invariant: "C-PROV-003", subject: "al:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/al_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-BASH": {id: "W-PROV-CHECKSUM-BASH", invariant: "C-PROV-003", subject: "bash:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/bash_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-BSL": {id: "W-PROV-CHECKSUM-BSL", invariant: "C-PROV-003", subject: "bsl:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/bsl_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-CLOJURE": {id: "W-PROV-CHECKSUM-CLOJURE", invariant: "C-PROV-003", subject: "clojure:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/clojure_lsp.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-CPP": {id: "W-PROV-CHECKSUM-CPP", invariant: "C-PROV-003", subject: "cpp:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/clangd_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-CUE": {id: "W-PROV-CHECKSUM-CUE", invariant: "C-PROV-003", subject: "cue:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/cue_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-DART": {id: "W-PROV-CHECKSUM-DART", invariant: "C-PROV-003", subject: "dart:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/dart_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-ELIXIR": {id: "W-PROV-CHECKSUM-ELIXIR", invariant: "C-PROV-003", subject: "elixir:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/elixir_tools/elixir_tools.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-GROOVY": {id: "W-PROV-CHECKSUM-GROOVY", invariant: "C-PROV-003", subject: "groovy:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/groovy_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-HAXE": {id: "W-PROV-CHECKSUM-HAXE", invariant: "C-PROV-003", subject: "haxe:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/haxe_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-HLSL": {id: "W-PROV-CHECKSUM-HLSL", invariant: "C-PROV-003", subject: "hlsl:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/hlsl_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-JAVA": {id: "W-PROV-CHECKSUM-JAVA", invariant: "C-PROV-003", subject: "java:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/eclipse_jdtls.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-KOTLIN": {id: "W-PROV-CHECKSUM-KOTLIN", invariant: "C-PROV-003", subject: "kotlin:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/kotlin_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-LATEX": {id: "W-PROV-CHECKSUM-LATEX", invariant: "C-PROV-003", subject: "latex:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/texlab_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-LUA": {id: "W-PROV-CHECKSUM-LUA", invariant: "C-PROV-003", subject: "lua:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/lua_ls.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-LUAU": {id: "W-PROV-CHECKSUM-LUAU", invariant: "C-PROV-003", subject: "luau:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/luau_lsp.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-MARKDOWN": {id: "W-PROV-CHECKSUM-MARKDOWN", invariant: "C-PROV-003", subject: "markdown:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/marksman.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-MATLAB": {id: "W-PROV-CHECKSUM-MATLAB", invariant: "C-PROV-003", subject: "matlab:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/matlab_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-PASCAL": {id: "W-PROV-CHECKSUM-PASCAL", invariant: "C-PROV-003", subject: "pascal:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/pascal_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-PHPACTOR": {id: "W-PROV-CHECKSUM-PHPACTOR", invariant: "C-PROV-003", subject: "php_phpactor:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/phpactor.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-POWERSHELL": {id: "W-PROV-CHECKSUM-POWERSHELL", invariant: "C-PROV-003", subject: "powershell:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/powershell_language_server.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-TERRAFORM": {id: "W-PROV-CHECKSUM-TERRAFORM", invariant: "C-PROV-003", subject: "terraform:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/terraform_ls.py", added: "2026-07-24"}
	"W-PROV-CHECKSUM-TOML": {id: "W-PROV-CHECKSUM-TOML", invariant: "C-PROV-003", subject: "toml:checksum-opaque", reason: "Structural extraction cannot prove the default-version checksum for this download path.", reference: "src/solidlsp/language_servers/taplo_server.py", added: "2026-07-24"}
}
