import logging
import os
import re
from pathlib import Path

from sensai.util.string import TextBuilder

log = logging.getLogger(os.path.basename(__file__))


def autogen_tool_list(target_filename = "01-about/035_tools.md"):
    from serena.tools import ToolRegistry

    target_file = Path(__file__).parent / target_filename
    with open(target_file, "w") as f:
        f.write("<!-- This file is auto-generated by docs/autogen_docs.py. Do not edit it manually. -->\n\n")
        f.write("# Tools\n\n")
        f.write("Find the full list of Serena's tools below.\n\n")
        f.write("Note that in most configurations, only a subset of these tools will be enabled simultaneously.\n")
        f.write("Tools marked as *optional* are disabled by default.\n\n")
        f.write("Tools marked as [BETA] were recently introduced and may not be fully robust yet.\n\n")
        tools_by_module = ToolRegistry().get_registered_tools_by_module()
        priority_modules = {"serena.tools.symbol_tools": 1, "serena.tools.jetbrains_tools": 2}

        text = TextBuilder()
        sorted_modules = sorted(tools_by_module.keys(), key=lambda m: (priority_modules.get(m, 3), m))
        for module in sorted_modules:
            tools = tools_by_module[module]
            module = module.replace("serena.tools.", "")
            text.with_line(f"* **{module}**")
            for tool in tools:
                info = ""
                if tool.is_optional:
                    info += " *(optional)*"
                if tool.is_beta:
                    info += " [BETA]"
                text.with_line(f"* `{tool.tool_name}`{info}: {tool.class_docstring}", indent=2)
        f.write(text.build())


def autogen_about_intro_features():
    readme_path = Path(__file__).parent.parent / "README.md"
    with open(readme_path, "r", encoding="utf-8") as f:
        readme_contents = f.read()

    match = re.search(r"<h3.*?>(.*?)</h3>(.*?)^## Programming.*?^(## Features.*?)^## ", readme_contents, re.DOTALL | re.MULTILINE)
    assert match, f"Failed to extract about texts from README.md. {__file__} probably needs to be updated."

    tagline = match.group(1).strip()
    about_text = match.group(2).strip()
    features_text = match.group(3).strip()

    autogen_info = f"<!-- This section is auto-generated by {__file__} from the root README.md; do not edit. -->\n\n"

    with open(Path(__file__).parent / "01-about" / "000_intro.md", "w", encoding="utf-8") as f:
        f.write(autogen_info)
        f.write("# About Serena\n\n")
        f.write(f"**{tagline}**\n\n")

        # adjust link
        about_text = about_text.replace("resources/serena-block-diagram.svg", "https://raw.githubusercontent.com/oraios/serena/main/resources/serena-block-diagram.svg")

        # remove centred links
        about_text = re.subn(r'^<div align="center">.*?</div>\s*<br>$', "", about_text, flags=re.MULTILINE | re.DOTALL)[0]

        # remove statements with links to quick start guide
        about_text = re.subn(r"^.*\[Quick Start.*?$", r"", about_text, flags=re.MULTILINE)[0]

        # remove callouts
        about_text = re.subn(r"^> \[!\w+\]\s+(^>.*?$)+", "", about_text, flags=re.MULTILINE)[0]

        # replace "Quick Demo" with "Video Introduction", removing the short video
        about_text = about_text.replace("# Quick Demo", "# Video Introduction")
        about_text = re.subn(r"^https://github.com/user-attachments/.*?$", "", about_text, flags=re.MULTILINE)[0]
        about_text = about_text.replace(":tv: Longer video:", "Watch our video:")

        # remove emojis (e.g. :tv:)
        about_text = re.subn(r":\w+:\s+", "", about_text)[0]


        f.write(f"{about_text}\n\n")

    jetbrains_marketplace_link = ('```{raw} html\n'
        '<p><a href="https://plugins.jetbrains.com/plugin/28946-serena/">'
        '<img style="background-color:transparent;" src="../_static/images/jetbrains-marketplace-button.png">'
        '</a></p>\n```')

    with open(Path(__file__).parent / "01-about" / "025_features.md", "w", encoding="utf-8") as f:
        f.write(autogen_info)
        features_text = re.subn(r"^#", r"", features_text, flags=re.MULTILINE)[0]
        features_text = re.subn(r"</?details>", "", features_text, flags=re.MULTILINE)[0]
        features_text = re.subn(r"<summary>.*?</summary>", "", features_text, flags=re.MULTILINE)[0]
        features_text = re.sub(r'<a href="https://plugins.jetbrains.com.*?</a>', jetbrains_marketplace_link, features_text, flags=re.DOTALL)
        f.write(f"{features_text}\n\n")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    autogen_about_intro_features()

    autogen_tool_list()
